Better archiving/extraction

diff --git a/lf/.config/lf/lfrc b/lf/.config/lf/lfrc
--- a/lf/.config/lf/lfrc
+++ b/lf/.config/lf/lfrc
@@ -257,19 +257,50 @@ cmd extract ${{
 # compress current file or selected files with tar and gunzip
 cmd tar ${{
     set -f
-    mkdir $1
-    cp -r $fx $1
-    tar czf $1.tar.gz $1
-    rm -rf $1
+    printf "Archive name (without .tar.gz): "
+    read archivename
+    [ -z "$archivename" ] && exit 1
+
+    tar czf "${archivename}.tar.gz" $fx
+
+    echo "Created '${archivename}.tar.gz'"
 }}
 
 # compress current file or selected files with zip
 cmd zip ${{
     set -f
-    mkdir $1
-    cp -r $fx $1
-    zip -r $1.zip $1
-    rm -rf $1
+    printf "Archive name (without .zip): "
+    read archivename
+    [ -z "$archivename" ] && exit 1
+
+    zip -r "${archivename}.zip" $fx
+
+    echo "Created '${archivename}.zip'"
+}}
+
+cmd extract-here ${{
+    set -f
+    # Loop over all selected items in $fx
+    for file in $fx; do
+        if [ -f "$file" ]; then
+            case "$file" in
+                *.tar.bz2) tar xjf "$file" ;;
+                *.tar.gz)  tar xzf "$file" ;;
+                *.bz2)     bunzip2 "$file" ;;
+                *.rar)     unrar x "$file" ;;
+                *.gz)      gunzip "$file"  ;;
+                *.tar)     tar xf "$file"  ;;
+                *.tbz2)    tar xjf "$file" ;;
+                *.tgz)     tar xzf "$file" ;;
+                *.zip)     unzip "$file"   ;;
+                *.Z)       uncompress "$file" ;;
+                *.7z)      7z x "$file"    ;;
+                *) echo "'$file' cannot be extracted by this command" ;;
+            esac
+        else
+            echo "'$file' is not a valid file"
+        fi
+    done
 }}
 
 # Play in mpv
